config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :pictures
  root 'pictures#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.order("created_at DESC")
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
    redirect_to pictures_path
    else
      redirect_to "users/#{current_user.id}"
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to user_path(@picture.user.id)
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :title).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures
    @picture = Picture.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ins</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="header-left">
      <h2><%= link_to "Instagram", root_path %></h2>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
      <ul>
        <li><%= link_to "Mypage", user_path(current_user.id) %></li>
        <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
        <ul>
          <li><%= link_to "サインイン", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </header>

<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<% @pictures.each do |picture| %>
<%= link_to image_tag(picture.image), picture_path(picture.id) %>
<% end %>

app/views/pictures/new.html.erb
<%= form_for @picture do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/pictures/show.html.erb
<%= image_tag @picture.image %>
<p><%= @picture.title %></p>

app/views/users/show.html.erb
<%= form_for @picture do |f| %>
  <%= f.file_field :image %>
  <% if @picture.errors.any? %>
  <%= @picture.errors.masagges %>
  <% end %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

<ul>
<% @pictures.each do |picture| %>
  <li style="list-style-type: none;"><%= image_tag picture.image %></li>
  <li style="list-style-type: none;"><%= picture.title %></li>
  <%= link_to "edit", edit_picture_path(picture.id) %>
  <%= link_to "delete", picture_path(picture.id), method: :delete, data: { confirm: "are you sure?" } %>
<% end %>

</ul>